import Head from 'next/head'
import React, { useContext } from 'react'
import Modal from '../components/modal'
import Sidebar from '../components/sidebar'
import SinglePost from '../components/singlePost'
import Trending from '../components/trending'
import { AppContext } from '../contexts/appcontext'

const PostPage = () => {

    const [appcontext] = useContext(AppContext)

    return (
        <div>
            <Head>
                <title>Twitter</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='relative max-w-[1400px] mx-auto'>
                <Sidebar/>
                <div className='flex gap-6'>
                    <SinglePost/>
                    <Trending/>
                    {appcontext?.isModalOpen && <Modal/>}
                </div>
            </main>
        </div>
    )
}

export default PostPage