import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Login from '../components/login';

export default function Home() {

  const {data:session} = useSession();

  if(!session) return <Login/>

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-bold underline">
        Hello world!
      </h1>
    </div>
  )
}
